class Pin:
    IN: int
    OUT: int

    def __init__(self, id, mode=None): ...
    def value(self, v=None): ...


class PWM:
    def __init__(self, pin, freq=1000): ...
    def duty(self, value: int): ...
    def duty_u16(self, value: int): ...


class UART:
    def __init__(self, uart_id, baudrate=115200, tx=None, rx=None, timeout=0, read_buf_len=0): ...
    def readline(self): ...
    def write(self, data): ...
