from typing import Optional


class NRF24L01:
	def __init__(self, spi, csn, ce, payload_size: int = 32) -> None: ...
	def set_channel(self, channel: int) -> None: ...
	def set_retries(self, delay_us: int, count: int) -> None: ...
	def open_tx_pipe(self, address: bytes) -> None: ...
	def open_rx_pipe(self, pipe_id: int, address: bytes) -> None: ...
	def start_listening(self) -> None: ...
	def stop_listening(self) -> None: ...
	def any(self) -> int: ...
	def send(self, buf: bytes) -> None: ...
	def recv(self) -> bytes: ...
