RGB565: int
QVGA: int

class _Blob:
	def cx(self) -> int: ...
	def cy(self) -> int: ...
	def w(self) -> int: ...
	def h(self) -> int: ...
	def pixels(self) -> int: ...
	def rect(self): ...


class _Image:
	def find_blobs(self, thresholds, pixels_threshold=0, area_threshold=0, merge=False): ...
	def draw_rectangle(self, rect, color=None): ...
	def draw_cross(self, x: int, y: int, color=None): ...
	def width(self) -> int: ...
	def height(self) -> int: ...


def reset(): ...

def set_pixformat(fmt): ...

def set_framesize(size): ...

def skip_frames(time=0): ...

def set_auto_whitebal(value): ...

def set_auto_gain(value): ...

def snapshot() -> _Image: ...
